Import Libraries

In [81]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


Load the dataset

In [82]:
def importdata():
    df = pd.read_csv('..\Machine_Learning_algos\weather.csv')
    return df

Transform non-numeric values(as long as they are hashable and comparable) to numeric values

In [83]:
def use_labelEncoder(df):
    Le = LabelEncoder()
    for i in df.columns:
        df[i] = Le.fit_transform(df[i])
    return df


Split the dataset into Train and Test

y - holds all the decisions.
X - holds the training data.

In [84]:
def splitdataset(balance_data):
    
    # Separating the target variable
    X = balance_data['Play Golf']
    y = balance_data.drop('Play Golf',axis=1)
  
    X_train, X_test, y_train, y_test = train_test_split( 
    X, y, test_size = 0.3, random_state = 100)
      
    return X, y, X_train, X_test, y_train, y_test

Perform training with GiniIndex

In [85]:
def train_using_gini(X_train, X_test, y_train):
        
        # Creating the classifier object
        clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)
        
        X_train = X_train.values.reshape(-1, 1)
        # Performing training
        clf_gini.fit(X_train, y_train)
        return clf_gini

Perform training with entropy

In [86]:
def train_using_entropy(X_train, X_test, y_train):
        
        # Decision tree with entropy
        clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = 3, min_samples_leaf = 5)
        
        X_train = X_train.values.reshape(-1, 1)
        # Performing training
        clf_entropy.fit(X_train, y_train)
        return clf_entropy

Make predictions

In [87]:
def prediction(X_test, clf_object):
    X_test = X_test.values.reshape(-1, 1)
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
    print("Predicted values:")
    print(y_pred)
    return y_pred

Calculate accuracy

In [88]:
def cal_accuracy(y_test, y_pred):
    y_test = y_test.values.reshape(-1, 1)
    y_pred = y_pred.reshape(-1, 1)
    print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
      
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
      
    print("Report : ",
    classification_report(y_test, y_pred))

Driver code

In [89]:

data = importdata()
data = use_labelEncoder(data)
# print("Data after LabelEncoder\n",data)
X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
clf_gini = train_using_gini(X_train, X_test, y_train)
clf_entropy = train_using_entropy(X_train, X_test, y_train)



# Operational Phase
print("Results Using Gini Index:")
# Prediction using gini
y_pred_gini = prediction(X_test, clf_gini)
cal_accuracy(y_test, y_pred_gini)


print("Results Using Entropy:")
# Prediction using entropy
y_pred_entropy = prediction(X_test, clf_entropy)
cal_accuracy(y_test, y_pred_entropy)

Results Using Gini Index:
Predicted values:
[[1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]]
Confusion Matrix:  [[4 2 1]
 [6 1 2]
 [0 2 2]]
Accuracy :  35.0
Report :                precision    recall  f1-score   support

           0       0.40      0.57      0.47         7
           1       0.20      0.11      0.14         9
           2       0.40      0.50      0.44         4

    accuracy                           0.35        20
   macro avg       0.33      0.39      0.35        20
weighted avg       0.31      0.35      0.32        20

Results Using Entropy:
Predicted values:
[[1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]
 [1 2 0 0]]
Confusion Matrix:  [[4 2 1]
 [6 1 2]
 [0 2 2]]
Accuracy :  35.0
Report :                precision    recall  f1-score   support

           0       0.40      0.57      0.47         7
           1       0.20      0.11      0.14         9
           2       0.40      0.50      0.44         4

    accuracy                           0.35        20
  