In [8]:
import numpy as np

1S Matrix

In [9]:
arr= np.array([[1,1,1],[1,1,1],[1,1,1]])
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
arr_1s = np.ones(5)
print(arr_1s)

[1. 1. 1. 1. 1.]


In [12]:
arr_1s.dtype

dtype('float64')

In [15]:
mx_1s = np.ones((2,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
mx_1s = np.ones((2,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]]


0S Matrix

In [17]:
mx_0s = np.zeros((2,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
mx_0s = np.zeros((2,4), dtype = bool)
print(mx_0s)

[[False False False False]
 [False False False False]]


In [19]:
mx_0s = np.zeros((2,4), dtype = str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']]


Empty Matrix

In [20]:
emp_mx = np.empty((3,3))
print(emp_mx)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.07502005e-321]
 [1.37959740e-306 2.29175545e-312 4.47590761e-091]]
