Random sampling

In [2]:
import numpy as np
import random

In [7]:
# random.random gives values between 0 and 1 
np.random.random(4)

array([0.08084135, 0.36104405, 0.53999513, 0.1868294 ])

In [8]:
np.random.random((3,3))

array([[0.10523597, 0.67995106, 0.25088074],
       [0.54617864, 0.03634822, 0.37035838],
       [0.84641954, 0.3802595 , 0.55221097]])

In [9]:
# if we want integer values use randint
np.random.randint(1,4)

1

In [16]:
# if we want integer values use randint
np.random.randint(1,4)

2

In [17]:
np.random.randint(1,4,(4,4))

array([[1, 2, 2, 2],
       [3, 1, 2, 1],
       [3, 2, 3, 2],
       [3, 1, 1, 2]])

In [18]:
# if we want integer values use randint
np.random.randint(1,4,(2,4,4))

array([[[2, 3, 1, 2],
        [1, 3, 2, 2],
        [1, 1, 3, 1],
        [3, 2, 3, 1]],

       [[2, 3, 2, 1],
        [2, 3, 1, 2],
        [1, 2, 1, 3],
        [1, 3, 2, 3]]])

In [19]:
np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


In [20]:
np.random.seed(10)
rd_3D_arr = np.random.randint(1,4, (2,4,4))
print(rd_3D_arr)
# The seed function accepts value up to  2^32 -1 (4294967295)

[[[2 2 1 1]
  [2 1 2 2]
  [1 2 2 3]
  [1 2 1 3]]

 [[1 3 1 1]
  [1 3 1 3]
  [3 2 1 1]
  [3 2 3 2]]]


np.random.rand()

In [21]:
arr_2D = np.random.rand(3,3) # return  3 x 3 matrix
print(arr_2D)

[[0.13145815 0.41366737 0.77872881]
 [0.58390137 0.18263144 0.82608225]
 [0.10540183 0.28357668 0.06556327]]


np.random.randn()

In [27]:
arr_2D = np.random.randn(3,3)
print(arr_2D)

[[ 0.7434177  -0.56543268  0.00785023]
 [-1.12679091  1.513816   -0.60729449]
 [ 0.4183223   0.98655675 -0.30135904]]


np.random.choice()

In [28]:
x = [1,2,3,4] # list
choice_from_x = np.random.choice(x) # retun random single item from sequence
print(choice_from_x )

2


In [29]:
for i in range(20):
    print(np.random.choice(x))

4
2
4
3
2
4
2
2
4
4
1
1
2
2
1
2
4
4
3
4


np.random.permutation()

In [30]:
x_permute = np.random.permutation(x)
print(x_permute)

[3 4 2 1]
