In [29]:
import numpy

arange()

In [30]:
# np.arrange(start,end,steps)
arr_1d = numpy.arange(1,13)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
even_arr = np.arange(0,13,2)
even_arr

array([ 0,  2,  4,  6,  8, 10, 12])

linespace()

In [32]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

reshape()

In [35]:
# if we have 1 d array and want to reshape it 
# to 2d, we use reshape
arr_1d.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [37]:
arr_1d.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [39]:
arr_1d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
# 1d to 3d
arr_1d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

ravel()

In [41]:
ar = np.arange(1,13).reshape(3,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# converts multi-D to 1D
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten()

In [44]:
# converts multi-D to 1D
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

transpose

In [47]:
ar.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])